-- Seed the 6 existing mock venues and their music-genre relationships.
-- Source of truth: constants/venues.ts.
--
-- - venues.id is generated by Postgres (gen_random_uuid()); the old numeric
--   mock ids are not preserved anywhere.
-- - city_id is resolved by joining on cities(country_id, name), using the
--   countries/cities already inserted by the earlier seed migration. No new
--   cities are created here.
-- - description, address, latitude, longitude, and opening_time are left
--   NULL: the mock data has no equivalent values for them.
-- - distance is intentionally not migrated; it's derived from the user's
--   location at query time, not stored data.
--
-- Duplicate-safety: a venue is only inserted if no existing row already has
-- the same (name, city_id) pair, so re-running this migration after a
-- successful run is a no-op. venue_music_genres also has ON CONFLICT DO
-- NOTHING as a second safeguard (its (venue_id, genre_id) primary key would
-- reject a true duplicate anyway).
--
-- Known limitation: if this migration is re-run after a *partial* failure
-- (e.g. venues inserted but the genre-link insert failed), venues that were
-- already inserted will be skipped by the (name, city_id) check, so their
-- genre links would not be retried. Given this is a one-time seed of 6
-- known venues, that edge case is not handled automatically here.

with source_venues (name, country_id, city_name, closing_time, genres) as (
  values
    ('Drugstore',       'RS', 'Belgrade',   '04:00'::time, array['Techno', 'House', 'Electro']::text[]),
    ('20/44',           'RS', 'Belgrade',   '03:00'::time, array['House', 'Tech House', 'Disco']::text[]),
    ('KST',              'RS', 'Belgrade',   '02:00'::time, array['Rock', 'Domestic', 'Alternative Rock']::text[]),
    ('GIGS',             'RS', 'Novi Sad',   '04:00'::time, array['Techno', 'House', 'Tech House']::text[]),
    ('The Quarter',      'RS', 'Novi Sad',   '02:00'::time, array['Rock', 'Indie Rock', 'Alternative Rock']::text[]),
    ('Paradise Garage',  'RS', 'Niš',        '03:00'::time, array['House', 'Techno', 'Disco']::text[])
),
resolved_venues as (
  select
    sv.name,
    sv.closing_time,
    sv.genres,
    c.id as city_id
  from source_venues sv
  join public.cities c
    on c.country_id = sv.country_id
   and c.name = sv.city_name
),
inserted_venues as (
  insert into public.venues (city_id, name, closing_time)
  select rv.city_id, rv.name, rv.closing_time
  from resolved_venues rv
  where not exists (
    select 1
    from public.venues existing
    where existing.name = rv.name
      and existing.city_id = rv.city_id
  )
  returning id, name, city_id
)
insert into public.venue_music_genres (venue_id, genre_id)
select iv.id, mg.id
from inserted_venues iv
join resolved_venues rv
  on rv.name = iv.name
 and rv.city_id = iv.city_id
join public.music_genres mg
  on mg.name = any(rv.genres)
on conflict (venue_id, genre_id) do nothing;
